[project]
name = "metarlgym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.5.2",
    "liger-kernel>=0.5.5",
    "peft>=0.15.1",
    "protobuf>=6.30.2",
    "rich>=14.0.0",
    "torch>=2.6.0",
    "trl>=0.16.0",
    "vllm>=0.8.2",
    "wandb>=0.12.16",
]
